jobs/common.sh: line 3: =/home/tntech.edu/namartinda42/research/logs: No such file or directory
Using TensorFlow backend.
Traceback (most recent call last):
  File "experiment.py", line 119, in <module>
    util.init_logging(args.log_path)
  File "/home/tntech.edu/namartinda42/research/bias/util.py", line 190, in init_logging
    file_handler = logging.FileHandler(log_path)
  File "/home/tntech.edu/namartinda42/.conda/envs/tensorflow-gpu/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/tntech.edu/namartinda42/.conda/envs/tensorflow-gpu/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/datagen_bias_as_tfidf.log'
Using TensorFlow backend.
Traceback (most recent call last):
  File "experiment.py", line 119, in <module>
    util.init_logging(args.log_path)
  File "/home/tntech.edu/namartinda42/research/bias/util.py", line 190, in init_logging
    file_handler = logging.FileHandler(log_path)
  File "/home/tntech.edu/namartinda42/.conda/envs/tensorflow-gpu/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/tntech.edu/namartinda42/.conda/envs/tensorflow-gpu/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/datagen_bias_as_w2v.log'
Using TensorFlow backend.
Traceback (most recent call last):
  File "experiment.py", line 119, in <module>
    util.init_logging(args.log_path)
  File "/home/tntech.edu/namartinda42/research/bias/util.py", line 190, in init_logging
    file_handler = logging.FileHandler(log_path)
  File "/home/tntech.edu/namartinda42/.conda/envs/tensorflow-gpu/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/tntech.edu/namartinda42/.conda/envs/tensorflow-gpu/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/datagen_bias_as_glove.log'
Using TensorFlow backend.
Traceback (most recent call last):
  File "experiment.py", line 119, in <module>
    util.init_logging(args.log_path)
  File "/home/tntech.edu/namartinda42/research/bias/util.py", line 190, in init_logging
    file_handler = logging.FileHandler(log_path)
  File "/home/tntech.edu/namartinda42/.conda/envs/tensorflow-gpu/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/tntech.edu/namartinda42/.conda/envs/tensorflow-gpu/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/datagen_bias_as_fasttext.log'
